<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartStudyPlanner.Application\SmartStudyPlanner.Application.csproj" />
    <ProjectReference Include="..\SmartStudyPlanner.Domain\SmartStudyPlanner.Domain.csproj" />
    <ProjectReference Include="..\SmartStudyPlanner.Infrastructure\SmartStudyPlanner.Infrastructure.csproj" />
  </ItemGroup>

</Project>
